name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        region: ${{ secrets.GCP_REGION }}

    - name: Build Docker image
      run: |
        cd node-apps/node-hello-1
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-repo/hello-world-app1 .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-repo/hello-world-app1
